# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MARRs1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
pod 'Google/SignIn', '~> 3.0.3'
pod 'RMYouTubeExtractor'
pod 'InstantSearchVoiceOverlay'
pod 'youtube-ios-player-helper'
pod 'RAMAnimatedTabBarController'
  target 'MARRs1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MARRs1UITests' do
    # Pods for testing
  end

end
